Add `store.KeyedErrorHealthCheckSource` interface and default implementation.
palantir/witchcraft-go-server pull request #160
Opened 2020-02-17 20:05 UTC by jamesross3

## Before this PR

## After this PR
==COMMIT_MSG==

==COMMIT_MSG==

## Possible downsides?

2020-02-18 10:59 UTC, CRogers reviewed
I am not the right person to review this. Commenting to clear review.

2020-02-18 13:52 UTC, jamesross3 commented
@nmiyake, @ashrayjain, and @splucs for review

2020-02-18 14:57 UTC, splucs commented
LGTM, but I can't approve :(

2020-02-18 14:57 UTC, splucs approved these changes

2020-02-18 16:55 UTC, nmiyake requested changes
Implementation looks good, but would like documentation improved a bit -- beyond the nits, would like better overall documentation that describes how the health check source operates/the scenarios in which it is useful. Basically, if someone who isn't familiar comes through and sees all these different health check sources, would be good if they could get a high-level overview of them without having to read the implementaiton.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-:-M0OD-a4981k6G-elVec:b9t0rqv)* status: all files reviewed, 4 unresolved discussions (waiting on @jamesross3)

___
*[status/health/store/keyed_error_source.go, line 26 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-M0OC4a30E8_A1wfKKJ0:-M0OC4a43s5g5FwMmg0d:b-8rw7pu) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/7a69c87af910cc8b54728373b0e4abefcf984390/status/health/store/keyed_error_source.go#L26)):*
> ```Go
> 
> // KeyedErrorSubmitter is a separate interface to allow method signatures to only accept the Submit functionality of
> // a KeyedErrorHealthCheckSource
> ```

nit: full sentence, so end with period.
___
*[status/health/store/keyed_error_source.go, line 28 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-M0OCM4w9DNmXNxKkMgA:-M0OCM4w9DNmXNxKkMgB:bnqh6p2) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/7a69c87af910cc8b54728373b0e4abefcf984390/status/health/store/keyed_error_source.go#L28)):*
> ```Go
> // a KeyedErrorHealthCheckSource
> type KeyedErrorSubmitter interface {
> 	Submit(key string, err error)
> ```

Can you add documentation to describe the contract of this function for an implementing interface?
___
*[status/health/store/keyed_error_source.go, line 31 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-M0OC6TW33hMkcgo0Hqk:-M0OC6TW33hMkcgo0Hql:b-cezn88) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/7a69c87af910cc8b54728373b0e4abefcf984390/status/health/store/keyed_error_source.go#L31)):*
> ```Go
> }
> 
> // KeyedErrorHealthCheckSource tracks errors by key to compute health status
> ```

Period at end
___
*[status/health/store/keyed_error_source.go, line 44 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-M0OC9CNBTQta0DyQdJQ:-M0OC9CNBTQta0DyQdJR:b-cezn88) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/7a69c87af910cc8b54728373b0e4abefcf984390/status/health/store/keyed_error_source.go#L44)):*
> ```Go
> }
> 
> // NewKeyedErrorHealthCheckSource creates a health messenger that tracks errors by keys to compute health status
> ```

Period at end


<!-- Sent from Reviewable.io -->

2020-02-18 18:55 UTC, jamesross3 commented
Responded to initial round of feedback.

2020-02-18 18:58 UTC, nmiyake requested changes
Question on documentation for the error case.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-:-M0OeVnr72q5fuscLR0c:b-r88bo2)* status: all files reviewed, 1 unresolved discussion (waiting on @jamesross3)

___
*[status/health/store/keyed_error_source.go, line 37 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/160#-M0OeN0j8tL4CvOfvX23:-M0OeN0j8tL4CvOfvX24:b-8w3a3m) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27d7614d1e34e5cfb0a4a34b3111787bcb6cf0a3/status/health/store/keyed_error_source.go#L37)):*
> ```Go
> // errors are stored. When computing health status, the KeyedErrorHealthCheckSource will return a
> // health status with state HealthStateHealthy if it has no error entries. If it has any error entries, it will return
> // a health status with the state HealthStateError.
> ```

In the second case, does it also detail the individual errors? That is, what is the visible/error output?


<!-- Sent from Reviewable.io -->

2020-02-18 19:38 UTC, jamesross3 commented
updated comment to explain the contents of the params field within the health status' health check when the state is `HealthStateError`.

2020-02-19 18:34 UTC, nmiyake approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/160)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-02-19 18:34 UTC, merged