Add anchored variant of NewHealthyIfNotAllErrorsSource
palantir/witchcraft-go-server pull request #163
Opened 2020-02-27 02:19 UTC by EdwinRobbins

## Before this PR

Existing healthyIfNotAllErrorsSource implementation allows single error to dominate starting window and windows after gaps which are larger than the grace period. This change allows for enforcing the grace period on these windows as well.

## After this PR
==COMMIT_MSG==

- Adds healthyIfNotAllErrorsSource option to have grace period respected for initial window and those after gaps
==COMMIT_MSG==

## Possible downsides?

Purely additive, no expected negative user impact

2020-02-27 11:35 UTC, fawind commented
Generally looks good but I'm not super familiar with witchcraft-go. I would suggest a second look from @dansanduleac maybe?

2020-02-28 17:41 UTC, jamesross3 approved these changes
Thanks for the documented tests 👍

2020-02-28 18:47 UTC, nmiyake requested changes
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/163)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @EdwinRobbins, @fawind, and @splucs)

___
*[status/health/window/error_source.go, line 127 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/163#-M1C6v6x-CsMo9wIr1Lz:-M1C6v6x-CsMo9wIr1M-:b-fs0r7e) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/589c1ba09c187e232c858ad53852abc4e389d9e6/status/health/window/error_source.go#L127)):*
> ```Go
> // NewAnchoredHealthyIfNotAllErrorsSource creates an healthyIfNotAllErrorsSource
> // with supplied checkType, using sliding window of size windowSize, which will
> // anchor healthy for the initial window or after gaps greater than windowSize
> ```

What does it mean to "anchor healthy"? I don't fully understand, so if you could explain it a bit more that would be great!


<!-- Sent from Reviewable.io -->

2020-02-28 18:56 UTC, EdwinRobbins commented
@nmiyake I've updated the godoc to make this more clear. In this case means to make the window evaluation forced to be at lease grace period window specified before it can report as unhealthy. It is "anchored" by a healthy check that is inserted at the start of new windows.

2020-02-28 18:58 UTC, nmiyake approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fawind and @splucs)



<!-- Sent from Reviewable.io -->

2020-02-28 18:59 UTC, merged

2020-02-28 18:59 UTC, svc-autorelease commented
Released [1.16.0](https://github.com/palantir/witchcraft-go-server/releases/tag/v1.16.0)

2020-02-28 19:26 UTC, splucs commented on status/health/window/error_source_test.go
> +				werror.ErrorWithContextParams(context.Background(), "Error #1"),
`context.Background` has no params, what's the point of adding these?

2020-02-28 19:28 UTC, EdwinRobbins commented on status/health/window/error_source_test.go
> +				werror.ErrorWithContextParams(context.Background(), "Error #1"),
the Error call is deprecated, this is just to remove the deprecated calls. Under the hood this is what Error is doing anyway.

2020-02-28 19:31 UTC, nmiyake commented on status/health/window/error_source_test.go
> +				werror.ErrorWithContextParams(context.Background(), "Error #1"),
Edwin is correct. We had this discussion on the thread that added the `ErrorWithContextParams` function. Technically, `werror.Error` isn't fully deprecated (it's fine to use in cases where no context is available), but from a practical perspective most callers should prefer the `ErrorWithContextParams` function, so we marked the other function as "deprecated" for now to provide better signal for current developers. Once we get a critical mass of usage of the newer approach, we may un-deprecate.

2020-03-02 13:35 UTC, ashrayjain commented
If i have errors (and only errors) at a freq equal to the window size, doesn't this make my health check always be green (incorrectly)?

2020-03-02 18:44 UTC, EdwinRobbins commented
> If i have errors (and only errors) at a freq equal to the window size, doesn't this make my health check always be green (incorrectly)?

There is a sampling behavior at work here. You'd only want to use a grace period that is at least 2x your health reporting rate, a la Nyquist sampling. It is possible for a user to configure this health check source in a way that may not alert them, but this is just to provide another option and it's up to users to choose and configure these as appropriate for their service