improvement: loggers emit sls.logging.length metric
palantir/witchcraft-go-server pull request #181
Opened 2020-05-06 18:23 UTC by ch-plattner

As part of the go infra tooling week, we are working on a feature that allows WGS to emit the `sls.logging.length` metric when logging a line.

This PR is for discussing a possible approach.

## After this PR
==COMMIT_MSG==

==COMMIT_MSG==

## Possible downsides?

2020-05-06 18:46 UTC, nmiyake requested changes
Thanks! I think the over-all approach looks good -- some minor feedback about adding documentation, but I think this makes sense as an approach.

Also, just to check, what verification did you end up doing to check that currently a single `Write` call does correspond to a single log line?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-:-M6fIaF_BxqR6lIPBkbL:b-ore08z)* status: all files reviewed, 4 unresolved discussions (waiting on @ch-plattner)

___
*[witchcraft/loggers.go, line 35 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fFYes8-b6zxpDvRU2:-M6fFYet8pxUXoz59dXz:b-x0vbs1) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/loggers.go#L35)):*
> ```Go
> )
> 
> func (s *Server) initLoggers(useConsoleLog bool, logLevel wlog.LogLevel) []metricloggers.MetricWriter {
> ```

Let's add documentation to the function to describe what it does and what it returns. Documentation should have really existed prior to this as well, but think it would be good particularly now that it returns a value.
___
*[witchcraft/loggers.go, line 84 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fHqq09t9pyFjOqmCi:-M6fHqq09t9pyFjOqmCj:b-tpbk57) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/loggers.go#L84)):*
> ```Go
> }
> 
> func newDefaultLogOutput(logOutputPath string, logToStdout bool, stdoutWriter io.Writer) metricloggers.MetricWriter {
> ```

Same in terms of adding documentation
___
*[witchcraft/internal/metricloggers/writer.go, line 25 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fIUGm7MAtNp0r6d4G:-M6fIUGm7MAtNp0r6d4H:b-6fpp9o) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/internal/metricloggers/writer.go#L25)):*
> ```Go
> var _ io.Writer = (*metricWriter)(nil)
> 
> type MetricWriter interface {
> ```

Let's add documentation for this as well
___
*[witchcraft/internal/metricloggers/writer.go, line 52 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fIPTO5vQSa-ZKwBG4:-M6fIPTO5vQSa-ZKwBG5:bpoy6ca) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/internal/metricloggers/writer.go#L52)):*
> ```Go
> 	if m.recorder != nil {
> 		// Commented out because I still need to fix the integration tests if we chose this approach
> 		//m.recorder.RecordSLSLogLength(n)
> ```

I think we should be good to go with this


<!-- Sent from Reviewable.io -->

2020-05-06 19:25 UTC, ch-plattner commented
@nmiyake I had written a very simple handrolled test to show that one Write call corresponded to one log. Updated it here: https://github.com/ch-plattner/witchcraft-go-server/commit/f60cba03de6c1352c66a40596c66d465b2a7bd30

I'd be happy to write more extensive testing and include it in this PR. I can also dig into the wlog-zap implementation

2020-05-06 20:09 UTC, ch-plattner reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/loggers.go, line 35 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fFYes8-b6zxpDvRU2:-M6fZFGB677cu4G6GMSn:bjwgev2) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/loggers.go#L35)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Let's add documentation to the function to describe what it does and what it returns. Documentation should have really existed prior to this as well, but think it would be good particularly now that it returns a value.
</blockquote></details>

Sounds good! Let me know what you think of what I've written up
___
*[witchcraft/loggers.go, line 84 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fHqq09t9pyFjOqmCi:-M6fWuHU3ncgEm6FYODe:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/loggers.go#L84)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Same in terms of adding documentation
</blockquote></details>

Done.
___
*[witchcraft/internal/metricloggers/writer.go, line 25 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fIUGm7MAtNp0r6d4G:-M6fYWiaC4mo-UVTLzP0:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/internal/metricloggers/writer.go#L25)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Let's add documentation for this as well
</blockquote></details>

Done.
___
*[witchcraft/internal/metricloggers/writer.go, line 52 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fIPTO5vQSa-ZKwBG4:-M6fYTb3E75E3eZu596Y:bnzngzb) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/internal/metricloggers/writer.go#L52)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

I think we should be good to go with this
</blockquote></details>

Sounds good! I'll fixed up the integration tests next


<!-- Sent from Reviewable.io -->

2020-05-06 22:12 UTC, nmiyake requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: all files reviewed, 4 unresolved discussions (waiting on @ch-plattner)

___
*[witchcraft/loggers.go, line 35 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fFYes8-b6zxpDvRU2:-M6g0NmL9hHmAndvbN9q:bpbe2f5) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/loggers.go#L35)):*
<details><summary><i>Previously, ch-plattner (Char) wrote…</i></summary><blockquote>

Sounds good! Let me know what you think of what I've written up
</blockquote></details>

Thanks, this is pretty good! Would suggest the following:

* State that the server's logger fields are being set
* Make it clear that provided logLevel is used only for service loggers

Hmm, in thinking about how to describe the return value, realize that there's a lot that's kind of packed in here... If we do initialize metrics first, is it correct that we won't have to return this and can isolate all logic in here and only do assignments once? If that's the case, I think that may be preferable.
___
*[witchcraft/loggers.go, line 93 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fvsUeBycnkR_yeHnv:-M6fvsUeBycnkR_yeHnw:b-kfclu9) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/loggers.go#L93)):*
> ```Go
> 
> // Returns a MetricWriter which can be used as the underlying writer for a logger.
> // If logToStdout is true, then the provided stdoutWriter is used within the MetricWriter.
> ```

Should expand this to be "if logToStdout is true or logToStdoutBasedOnEnv() returns true"
___
*[witchcraft/internal/metricloggers/writer.go, line 25 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6g-45MAzJTECvbkngM:-M6g-45MAzJTECvbkngN:bej5afp) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/internal/metricloggers/writer.go#L25)):*
> ```Go
> var _ io.Writer = (*metricWriter)(nil)
> 
> // MetricWriter can be used for SLS logging. It emits metrics about the length of the lines writen.
> ```

Let's change "emits" to "records" -- for metrics, "emits" has the connotation of writing the output, which this technically does not do.
___
*[witchcraft/internal/metricloggers/writer.go, line 28 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6g-Fne-AQhsp8-kQ7a:-M6g-Fne-AQhsp8-kQ7b:bbm8acd) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/internal/metricloggers/writer.go#L28)):*
> ```Go
> type MetricWriter interface {
> 	io.Writer
> 	// SetMetricRegistry initializes the metric registry used for emitting metrics.
> ```

Would update the interface documentation to be more generic -- would state that it sets the metrics registry and that, if the registry is `nil`, no metrics are recorded.
___
*[witchcraft/internal/metricloggers/writer.go, line 39 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6g-V0LEEQCUlJI9bWT:-M6g-V0LEEQCUlJI9bWU:bmurgtw) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/internal/metricloggers/writer.go#L39)):*
> ```Go
> }
> 
> // NewMetricWriter returns a MetricWriter that delegates to writer, and emits SLS log line length
> ```

"emits" -> "records"


<!-- Sent from Reviewable.io -->

2020-05-06 23:10 UTC, ch-plattner reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/loggers.go, line 35 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fFYes8-b6zxpDvRU2:-M6gEs3E1u37BRn0oZc0:b-bri0y1) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/71465e6c8e7ee081a4cf518a70eae596d7b9ed2c/witchcraft/loggers.go#L35)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Thanks, this is pretty good! Would suggest the following:

* State that the server's logger fields are being set
* Make it clear that provided logLevel is used only for service loggers

Hmm, in thinking about how to describe the return value, realize that there's a lot that's kind of packed in here... If we do initialize metrics first, is it correct that we won't have to return this and can isolate all logic in here and only do assignments once? If that's the case, I think that may be preferable.
</blockquote></details>

Talked offline -- removing the return. Updated the comment as well!
___
*[witchcraft/loggers.go, line 93 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6fvsUeBycnkR_yeHnv:-M6g7geWAajpyX43RjqR:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/loggers.go#L93)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Should expand this to be "if logToStdout is true or logToStdoutBasedOnEnv() returns true"
</blockquote></details>

Done.
___
*[witchcraft/internal/metricloggers/writer.go, line 25 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6g-45MAzJTECvbkngM:-M6g7ydc7AqN0gRWD1jp:b9z8p3u) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/internal/metricloggers/writer.go#L25)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Let's change "emits" to "records" -- for metrics, "emits" has the connotation of writing the output, which this technically does not do.
</blockquote></details>

Great -- did that everywhere in this file!
___
*[witchcraft/internal/metricloggers/writer.go, line 28 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6g-Fne-AQhsp8-kQ7a:-M6gElxP-1K-C0JyYVpX:b-ovrdjd) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/internal/metricloggers/writer.go#L28)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Would update the interface documentation to be more generic -- would state that it sets the metrics registry and that, if the registry is `nil`, no metrics are recorded.
</blockquote></details>

Ended up deleting this function because its no longer necessary when we just set the instrumented loggers directly
___
*[witchcraft/internal/metricloggers/writer.go, line 39 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6g-V0LEEQCUlJI9bWT:-M6g7qVz-dPwOMQVT9SQ:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/4a2e43e8b602790d752e627545acee0365b7a71d/witchcraft/internal/metricloggers/writer.go#L39)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

"emits" -> "records"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-06 23:24 UTC, nmiyake requested changes
> Reviewed 4 of 4 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @ch-plattner and @nmiyake)

___
*[witchcraft/loggers.go, line 43 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gGlmzDZBYco_aNyT_:-M6gGln-EAIlFX2laPFv:b-ymbj5n) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/loggers.go#L43)):*
> ```Go
> // If useConsoleLog is true, then all loggers log to stdout.
> // The provided logLevel is used when initializing the service logs only.
> func (s *Server) initLoggers(registry metrics.Registry, useConsoleLog bool, logLevel wlog.LogLevel) {
> ```

Bit of a nit, but let's have `registry` be the last argument (since I think it's the most "incidental" one to the logic of the function)
___
*[witchcraft/loggers.go, line 85 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gGzod44bhkvdekq23:-M6gGzod44bhkvdekq24:b-s6d0r7) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/loggers.go#L85)):*
> ```Go
> // If either logToStdout or logToStdoutBasedOnEnv() is true, then the returned Writer will delegate to stdoutWriter.
> // Otherwise, it will use a default writer that writes to slsFilename.
> func newDefaultLogOutputWriter(registry metrics.Registry, slsFilename string, logToStdout bool, stdoutWriter io.Writer) io.Writer {
> ```

Now that this is back to being a normal `io.Writer`, let's keep this function exactly the same as before and then do the `NewMetricWriter` wrapping in the implementation of `logWriterFn` (the place that currently calls this function).

Even though it's not that big of a code difference, I think it creates cleaner conceptual separation.
___
*[witchcraft/server_metrics.go, line 100 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gH_Zc5kqIEIYgkKuR:-M6gH_Zd9ggobpQjAy8f:b-y9mckg) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/server_metrics.go#L100)):*
> ```Go
> 		}
> 		// s.metricLogger is not guaranteed to be non-nil at this point, so we use the logger from the ctx.
> 		metric1log.FromContext(ctx).Metric(metricID, metricType, metric1log.Values(valuesToUse), metric1log.Tags(tags.ToMap()))
> ```

How will this work? Since `ctx` doesn't have loggers set on it, I think this will always produce the default one.

I think the previous implementation is correct, but we'll want to add a non-nil check:

```
metricLogger := s.metircLogger
if metricLogger != nil {
   ...
}
```
___
*[witchcraft/witchcraft.go, line 581 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gHxJV2_utkjfxRcOw:-M6gHxJV2_utkjfxRcOx:bnga9zh) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/witchcraft.go#L581)):*
> ```Go
> 	ctx = metrics.WithRegistry(ctx, metricsRegistry)
> 
> 	// initialize loggers.
> ```

nit: when it's a simple/small statement like this, don't need period (and that's more consistent with style of the rest of the comments in this function)


<!-- Sent from Reviewable.io -->

2020-05-06 23:30 UTC, ch-plattner reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/loggers.go, line 43 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gGlmzDZBYco_aNyT_:-M6gJ1bL1hK7zEx6WC7H:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/loggers.go#L43)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Bit of a nit, but let's have `registry` be the last argument (since I think it's the most "incidental" one to the logic of the function)
</blockquote></details>

Done.
___
*[witchcraft/loggers.go, line 85 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gGzod44bhkvdekq23:-M6gIpHe-hkVBJzLTY0a:b-pd7499) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/loggers.go#L85)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Now that this is back to being a normal `io.Writer`, let's keep this function exactly the same as before and then do the `NewMetricWriter` wrapping in the implementation of `logWriterFn` (the place that currently calls this function).

Even though it's not that big of a code difference, I think it creates cleaner conceptual separation.
</blockquote></details>

sure, I think that makes sense! done!
___
*[witchcraft/server_metrics.go, line 100 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gH_Zc5kqIEIYgkKuR:-M6gIiyZDSDzqvRp3JOR:bvj2pb8) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0887e55347ec2bc024281b543fb760b15fdbae4f/witchcraft/server_metrics.go#L100)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

How will this work? Since `ctx` doesn't have loggers set on it, I think this will always produce the default one.

I think the previous implementation is correct, but we'll want to add a non-nil check:

```
metricLogger := s.metircLogger
if metricLogger != nil {
   ...
}
```
</blockquote></details>

oops you're right. I just noticed that after requesting your review, but it should be fixed now!


<!-- Sent from Reviewable.io -->

2020-05-07 00:02 UTC, nmiyake requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: all files reviewed, 1 unresolved discussion (waiting on @ch-plattner)

___
*[witchcraft/server_metrics.go, line 105 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/181#-M6gQe-N5recQafFS1mh:-M6gQe-OC3HxcBICMoMK:bw4moxk) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/771d450f78499034ad9a9e302da2c6bedae27efa/witchcraft/server_metrics.go#L105)):*
> ```Go
> 		if metricLogger == nil {
> 			// s.metricLogger is not guaranteed to be non-nil at this point.
> 			metricLogger = metric1log.FromContext(ctx)
> ```

If `metirLogger` is `nil` here, I think we should just omit the metric logging, since I'm not sure that we would always trust what the default provider would give us. I think this is also pretty safe in this case since we control all of the init logic. So, would flip conditional to `!=` and move the `metricLogger.Metric` call inside.


<!-- Sent from Reviewable.io -->

2020-05-07 06:01 UTC, nmiyake approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/181)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-05-07 06:01 UTC, merged

2020-05-07 15:09 UTC, nmiyake commented
@ch-plattner unfortunately looks like the test that was added may be flakey -- in the [CircleCI builds for the addLoggers branch](https://circleci.com/gh/palantir/workflows/witchcraft-go-server/tree/addLoggers), the test failed in [one run](https://circleci.com/workflow-run/dcb705ef-5b8e-4f05-8a3e-856152d68abe) but then [succeeded when retriggered](https://circleci.com/workflow-run/c61fe84a-90c3-4972-9360-09f003f9d4f8).

[Output](https://circleci.com/gh/palantir/witchcraft-go-server/1885):

```
Failed
{metric.1 2020-05-07T06:27:50.609240595Z logging.sls.length histogram map[count:1 max:524375 p95:524375 p99:524375] map[type:audit] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.609374244Z logging.sls.length histogram map[count:1 max:524429 p95:524429 p99:524429] map[type:trace] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.722334812Z logging.sls.length histogram map[count:1 max:524375 p95:524375 p99:524375] map[type:audit] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.722388344Z logging.sls.length histogram map[count:7 max:204 p95:204 p99:204] map[type:metrics] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.72240098Z logging.sls.length histogram map[count:1 max:524429 p95:524429 p99:524429] map[type:trace] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.823111106Z logging.sls.length histogram map[count:1 max:524375 p95:524375 p99:524375] map[type:audit] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.823211076Z logging.sls.length histogram map[count:15 max:204 p95:204 p99:204] map[type:metrics] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.823228341Z logging.sls.length histogram map[count:1 max:524429 p95:524429 p99:524429] map[type:trace] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.908847624Z logging.sls.length histogram map[count:1 max:524375 p95:524375 p99:524375] map[type:audit] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.908899687Z logging.sls.length histogram map[count:23 max:204 p95:204 p99:204] map[type:metrics] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.90891984Z logging.sls.length histogram map[count:1 max:229 p95:229 p99:229] map[type:service] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:50.908978547Z logging.sls.length histogram map[count:1 max:524429 p95:524429 p99:524429] map[type:trace] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:51.008882536Z logging.sls.length histogram map[count:1 max:524375 p95:524375 p99:524375] map[type:audit] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:51.008929239Z logging.sls.length histogram map[count:33 max:204 p95:204 p99:204] map[type:metrics] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:51.008941872Z logging.sls.length histogram map[count:1 max:403 p95:403 p99:403] map[type:request] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:51.008970112Z logging.sls.length histogram map[count:1 max:229 p95:229 p99:229] map[type:service] <nil> <nil> <nil> map[]}
{metric.1 2020-05-07T06:27:51.008979961Z logging.sls.length histogram map[count:3 max:524429 p95:524429 p99:524429] map[type:trace] <nil> <nil> <nil> map[]}
    TestMetricWriter: metrics_test.go:255: 
```

2020-05-07 16:26 UTC, ch-plattner commented
@nmiyake hm, I wonder why Trace logs occur in some runs but not other runs. we could remove the calls to Trace? I don't think the audit logger is actually used for logging anywhere in WGS

Alternatively, we could remove the integration test entirely and replace it with a unit test for the metric writter