Feature: Add HealthStatusChangeHandler interface.
palantir/witchcraft-go-server pull request #195
Opened 2020-07-10 22:48 UTC by jamesross3

Enable HealthStatusChangeHandler registration.

## Before this PR
Before this PR, we did not expose any ability for custom handling of changes to health status.

## After this PR
Enable registration of HealthStatusChangeHandlers for witchcraft servers. This enables the future addition of a diagnostic logging health status change handler as described [here](https://github.com/palantir/witchcraft-go-server/issues/194).
==COMMIT_MSG==
==COMMIT_MSG==

## Possible downsides?

2020-07-10 23:07 UTC, bmoylan requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/195)* status: all files reviewed, 2 unresolved discussions (waiting on @jamesross3)

___
*[status/status.go, line 91 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-MBuxraB2NGy15OkxndE:-MBuxraB2NGy15OkxndF:b-1m3jo9) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/dd98b02d157831d7e72131df91eaeaa5096eac0b/status/status.go#L91)):*
> ```Go
> 		check:                     checkSource,
> 		previousHealth:            previousHealth,
> 		healthStatusChangeHandler: multiHealthStatusChangeHandler(allHandlers),
> ```

nit: `changeHandler` is shorter
___
*[status/status.go, line 100 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-MBuyFuP4bvyyqIHzpJg:-MBuyFuP4bvyyqIHzpJh:bokytgd) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/dd98b02d157831d7e72131df91eaeaa5096eac0b/status/status.go#L100)):*
> ```Go
> 	if previousHealth != nil {
> 		if previousHealthTyped, ok := previousHealth.(health.HealthStatus); ok {
> 			logIfHealthChanged(req.Context(), previousHealthTyped, metadata)
> ```

Shouldn't this be calling the stored handler, which includes the logging?


<!-- Sent from Reviewable.io -->

2020-07-11 14:58 UTC, jamesross3 reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/195)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[status/status.go, line 91 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-MBuxraB2NGy15OkxndE:-MByN0uz1KUw6FOOMBMp:bb7f2mf) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/dd98b02d157831d7e72131df91eaeaa5096eac0b/status/status.go#L91)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

nit: `changeHandler` is shorter
</blockquote></details>

done
___
*[status/status.go, line 100 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-MBuyFuP4bvyyqIHzpJg:-MByN1W06Q7vwbwsWmny:bu2rdmx) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/dd98b02d157831d7e72131df91eaeaa5096eac0b/status/status.go#L100)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Shouldn't this be calling the stored handler, which includes the logging?
</blockquote></details>

whoops done


<!-- Sent from Reviewable.io -->

2020-07-13 15:56 UTC, bmoylan commented
___
*[status/status.go, line 100 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-MC7sezI1KPQfnlCaM_g:-MC7sezI1KPQfnlCaM_h:b-gnpgqz) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ea0a61532c3f4e63accd34e2ac33b472d327b9a5/status/status.go#L100)):*
> ```Go
> 	if previousHealth != nil {
> 		if previousHealthTyped, ok := previousHealth.(health.HealthStatus); ok {
> 			h.changeHandler.HandleHealthStatusChange(req.Context(), previousHealthTyped, metadata)
> ```

Do we want to call this for every result or only when the checks differ? The contract should probably be added to the docs for the HealthStatusChangeHandler type and/or WithHealthStatusChangeHandler()


<!-- Sent from Reviewable.io -->

2020-07-13 15:56 UTC, bmoylan reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/195)* status: all files reviewed, 1 unresolved discussion (waiting on @jamesross3)



<!-- Sent from Reviewable.io -->

2020-07-13 17:52 UTC, bmoylan reviewed
just some docs then we should be gtg!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-:-MC8IZe3DV8viKHHkXAN:b40uq6m)* status: all files reviewed, 1 unresolved discussion (waiting on @jamesross3)

___
*[witchcraft/witchcraft.go, line 500 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-MC8IV52BvT-TMYmTj4p:-MC8IV52BvT-TMYmTj4q:b-yayki0) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/c8d3af4f157ffa0ec5379dc76b99c3973c052304/witchcraft/witchcraft.go#L500)):*
> ```Go
> }
> 
> func (s *Server) WithHealthStatusChangeHandlers(handlers ...status.HealthStatusChangeHandler) *Server {
> ```

Can you add docs explaining what these do and when they're called?


<!-- Sent from Reviewable.io -->

2020-07-13 18:28 UTC, bmoylan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/195#-:-MC8Qm9gDOeKUf97THjH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-07-13 18:40 UTC, jamesross3 commented
==MERGE_WHEN_READY==

2020-07-13 18:41 UTC, merged