Add middleware to add HSTS to all responses
palantir/witchcraft-go-server pull request #520
Opened 2022-10-12 16:16 UTC by andybradshaw

## Before this PR

## After this PR

==COMMIT_MSG==
Add middleware to add HTTP strict transport security to all responses
==COMMIT_MSG==

## Possible downsides?

2022-10-12 23:41 UTC, tabboud requested changes

2022-10-12 23:41 UTC, tabboud commented on witchcraft/internal/middleware/request.go
> +		rw.Header().Set(strictTransportSecurityHeader, strictTransportSecurityValue)
I am pretty sure this needs to be set before `ServeHTTP`

2022-10-12 23:41 UTC, tabboud commented on witchcraft/internal/middleware/request_test.go
> +	assert.Equal(t, w.Header().Get("Strict-Transport-Security"), "max-age=31536000")
use `w.Result().Header["Strict-Transport-Security"]` so that you are inspecting the response headers.

2022-11-02 00:02 UTC, splucs approved these changes

2022-11-02 00:02 UTC, merged

2022-11-02 00:02 UTC, svc-autorelease commented
Released [2.54.0](https://github.com/palantir/witchcraft-go-server/releases/tag/v2.54.0)