Add inflight request ratelimiter middleware
palantir/witchcraft-go-server pull request #67
Opened 2019-04-14 01:19 UTC by bmoylan

An optional middleware for returning 429 when there are too many requests in flight.

2019-04-15 17:10 UTC, nmiyake requested changes
On-board with the goal, but some questions/feedback on the initial implementation

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-:-LcWybzA4SVyb-XYtB6m:b-pr2uzf)* status: all files reviewed, 8 unresolved discussions (waiting on @bmoylan and @chewr)

___
*[witchcraft/ratelimit/middleware.go, line 29 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWuNViA6r_GXF5x_2q:-LcWuNViA6r_GXF5x_2r:br0z8cw) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L29)):*
> ```Go
> type MatchFunc func(req *http.Request, vals wrouter.RequestVals) bool
> 
> var MatchReadonly MatchFunc = func(req *http.Request, vals wrouter.RequestVals) bool {
> ```

nit: prefer `ReadOnly`, as the word is compound ("read-only")
___
*[witchcraft/ratelimit/middleware.go, line 37 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWuWd70ClylhZWz7BN:-LcWuWd70ClylhZWz7BO:buw5jeg) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L37)):*
> ```Go
> }
> 
> // NewInflightLimitMiddleware returns a middleware which counts and limits the number of
> ```

Would like the name to convey that it limits requests. I feel like one of:

* `NewRequestLimitMiddleware`
* `NewActiveRequestLimitMiddleware`
* `NewInFlightRequestLimitMiddleware`

might make the meaning clearer.

If we do use in-flight, as a nit, would prefer `InFlight` as capitalization and `in-flight` as documentation usage. I know that some sources list "inflight" as a valid word, but I see "in-flight" as a pretty common usage as well (including in Go docs: https://golang.org/pkg/net/http/#Transport.CancelRequest), and feel that compound adjectives should generally be hyphenated.
___
*[witchcraft/ratelimit/middleware.go, line 38 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWtBOy6EIfy7JeSXDQ:-LcWtBOy6EIfy7JeSXDR:b-8g99df) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L38)):*
> ```Go
> 
> // NewInflightLimitMiddleware returns a middleware which counts and limits the number of
> // inflight requests that match a the provided MatchFunc filter. If health is non-nil,
> ```

nit: name used here ("health") and parameter name ("healtcheck") should match.
___
*[witchcraft/ratelimit/middleware.go, line 39 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWtLlj6SoF4_P8wTJN:-LcWtLlj6SoF4_P8wTJO:botwkfi) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L39)):*
> ```Go
> // NewInflightLimitMiddleware returns a middleware which counts and limits the number of
> // inflight requests that match a the provided MatchFunc filter. If health is non-nil,
> // it will be set to REPAIRING when the middleware returns StatusTooManyRequests (429),
> ```

I think the documentation should also note the behavior that:

* Health is set to "Healthy" on construction by this function
* Health is set to "Healthy" 
___
*[witchcraft/ratelimit/middleware.go, line 49 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWs_w8Ay9fYUR1Hhe7:-LcWs_w8Ay9fYUR1Hhe8:b1yfb1z) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L49)):*
> ```Go
> 		Health:  healthcheck,
> 	}
> 	healthcheck.Healthy()
> ```

Needs a `nil` check to ensure that this won't panic if `healthcheck` is `nil` (function documentation implies that it can be `nil`, and all accesses in `ServeHTTP` are checked for `nil`)
___
*[witchcraft/ratelimit/middleware.go, line 62 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWxgOE4aGRyT3Mmp6X:-LcWxgOE4aGRyT3Mmp6Y:bbkm19) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L62)):*
> ```Go
> 
> func (l *limiter) ServeHTTP(rw http.ResponseWriter, req *http.Request, reqVals wrouter.RequestVals, next wrouter.RouteRequestHandler) {
> 	if l.Matches(req, reqVals) {
> ```

This will panic if the `MatchFunc` provided by the user in the constructor is `nil`.

Should either change the constructor to return an `error` and reject `nil` values, or change behavior to something like saying that a `nil` match function will match all requests (and document)
___
*[witchcraft/ratelimit/middleware.go, line 68 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWvygw6TmR4_QCXnLH:-LcWvygw6TmR4_QCXnLI:bhk9361) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L68)):*
> ```Go
> 		if current > l.Limit {
> 			msg := "Throttling due to too many inflight requests"
> 			if l.Health != nil && l.Health.Status() != health.HealthStateRepairing {
> ```

In this check and the previous check, is there any reason to perform the check that the state isn't already the target state?

Also, I don't believe that the get (`Status()`) and set (`SetHealth()`) functions are thread-safe themselves, so the check-and-set here and below where health is set could race (we may need to be somewhat concerned about this given that handlers are very much expected to run concurrently in multiple routines)
___
*[witchcraft/ratelimit/middleware.go, line 82 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWwRTDCoucDRcSOlG3:-LcWwRTDCoucDRcSOlG4:b-wr1ykj) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L82)):*
> ```Go
> 		// Mark ourselves healthy!
> 		if l.Health != nil && l.Health.Status() != health.HealthStateHealthy {
> 			l.Health.Healthy()
> ```

Big-picture question: what (if any) are the expectations for the health state after a sequence of actions?

Here's a possible edge case:

* Assume rate limit is 10 and server starts with 0 requests.
* Server gets 11 requests that match the filter, where first 10 are long-running
* When 11th request comes in, counter is incremented to 11 and health is set to "REPAIRING"
* All 11 requests complete and exit, and counter goes down to 0

In this scenario, the health will be marked as "REPAIRING" until the next matching request.

There probably isn't too much down-side here, but just wanted to clarify the contract/expectation.


<!-- Sent from Reviewable.io -->

2019-04-16 20:20 UTC, bmoylan reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @chewr and @nmiyake)

___
*[integration/ratelimit_test.go, line 118 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbnaBA1ul3bxN20CBW:-LcbnaBA1ul3bxN20CBX:bwzwm07) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/integration/ratelimit_test.go#L118)):*
> ```Go
> 	resp3 := doPost()
> 	require.Equal(t, http.StatusTooManyRequests, resp3.StatusCode, "expected third POST request to be rate limited")
> 	requireRepairing("expected repairing after throttled response")
> ```

I had to remove these checks because the middleware is so fast that it doesn't leave any leftover state to check after the request returns... ideas welcome for how to better test the health interaction
___
*[witchcraft/ratelimit/middleware.go, line 29 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWuNViA6r_GXF5x_2q:-LcZP04gBWm5xcWUtL8N:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L29)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

nit: prefer `ReadOnly`, as the word is compound ("read-only")
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 37 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWuWd70ClylhZWz7BN:-LcZUQFv3jPGandVW7co:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L37)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Would like the name to convey that it limits requests. I feel like one of:

* `NewRequestLimitMiddleware`
* `NewActiveRequestLimitMiddleware`
* `NewInFlightRequestLimitMiddleware`

might make the meaning clearer.

If we do use in-flight, as a nit, would prefer `InFlight` as capitalization and `in-flight` as documentation usage. I know that some sources list "inflight" as a valid word, but I see "in-flight" as a pretty common usage as well (including in Go docs: https://golang.org/pkg/net/http/#Transport.CancelRequest), and feel that compound adjectives should generally be hyphenated.
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 38 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWtBOy6EIfy7JeSXDQ:-LcZPC9V4DNQ3PA_qcNi:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L38)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

nit: name used here ("health") and parameter name ("healtcheck") should match.
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 39 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWtLlj6SoF4_P8wTJN:-LcZV0X37KcEx8hkDnpW:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L39)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

I think the documentation should also note the behavior that:

* Health is set to "Healthy" on construction by this function
* Health is set to "Healthy" 
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 49 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWs_w8Ay9fYUR1Hhe7:-LcZV1C29tbBoFqSqiSM:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L49)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Needs a `nil` check to ensure that this won't panic if `healthcheck` is `nil` (function documentation implies that it can be `nil`, and all accesses in `ServeHTTP` are checked for `nil`)
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 62 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWxgOE4aGRyT3Mmp6X:-LcZV2JT3fJBZxUs0iZz:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L62)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This will panic if the `MatchFunc` provided by the user in the constructor is `nil`.

Should either change the constructor to return an `error` and reject `nil` values, or change behavior to something like saying that a `nil` match function will match all requests (and document)
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 68 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWvygw6TmR4_QCXnLH:-LcZVfR76ev6LO9myxZO:bf7c12u) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L68)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

In this check and the previous check, is there any reason to perform the check that the state isn't already the target state?

Also, I don't believe that the get (`Status()`) and set (`SetHealth()`) functions are thread-safe themselves, so the check-and-set here and below where health is set could race (we may need to be somewhat concerned about this given that handlers are very much expected to run concurrently in multiple routines)
</blockquote></details>

I did it this way because it's guarded by a RWLock, so the read path should not contend for the lock and there should be relatively few writers. https://github.com/palantir/witchcraft-go-server/blob/develop/status/reporter/reporter.go#L138-L148
___
*[witchcraft/ratelimit/middleware.go, line 82 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWwRTDCoucDRcSOlG3:-LcZVwNg-9TWwmIuAd38:bo7dm68) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L82)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Big-picture question: what (if any) are the expectations for the health state after a sequence of actions?

Here's a possible edge case:

* Assume rate limit is 10 and server starts with 0 requests.
* Server gets 11 requests that match the filter, where first 10 are long-running
* When 11th request comes in, counter is incremented to 11 and health is set to "REPAIRING"
* All 11 requests complete and exit, and counter goes down to 0

In this scenario, the health will be marked as "REPAIRING" until the next matching request.

There probably isn't too much down-side here, but just wanted to clarify the contract/expectation.
</blockquote></details>

Great question. I've updated the logic to update the health status in the deferred function (`decrement`) so that each request is more atomically net-zero.


<!-- Sent from Reviewable.io -->

2019-04-16 20:32 UTC, nmiyake commented
___
*[witchcraft/ratelimit/middleware.go, line 68 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcWvygw6TmR4_QCXnLH:-LcbqBS64zgoFqtn9n0u:b-xju14) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/witchcraft/ratelimit/middleware.go#L68)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

I did it this way because it's guarded by a RWLock, so the read path should not contend for the lock and there should be relatively few writers. https://github.com/palantir/witchcraft-go-server/blob/develop/status/reporter/reporter.go#L138-L148
</blockquote></details>

Oh great, my mistake -- didn't know that the reporter itself was implemented in a thread-safe way. Great!


<!-- Sent from Reviewable.io -->

2019-04-16 20:54 UTC, nmiyake requested changes
Thanks! Main issue is one flagged by your issue with writing the test -- I think that the condition for triggering repairing state may need to be shifted by one to provide better semantics/signaling.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-:-LcbvFIY8g7Hb0Nml_WN:btvuumn)* status: all files reviewed, 6 unresolved discussions (waiting on @bmoylan and @chewr)

___
*[integration/ratelimit_test.go, line 118 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbnaBA1ul3bxN20CBW:-Lcbsys77W4pjhhik-Xq:bvvh88z) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/integration/ratelimit_test.go#L118)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

I had to remove these checks because the middleware is so fast that it doesn't leave any leftover state to check after the request returns... ideas welcome for how to better test the health interaction
</blockquote></details>

I think this is actually exposing a possible issue with the underlying logic!

As you point out, whenever a request that causes throttling comes in, the function immediately returns an error response and terminates, and sets the service back to "healthy". I think the logic should probably be changed such that the state is only set to healthy when the connection count is 1 less than the limit (rather than the limit itself).

Consider the case where the limit is 10 and we have 10 long-running requests that are effectively hogging all of the connections. In this case, the status would be "healthy", but every subsequent request that comes in will be throttled, set status to "repairing" for a fraction of a second, but then decrement and go back to "healthy" again.

I think the semantic should instead be that the service is "repairing" if it's at capacity (if subsequent matching requests will be throttled) -- so, if the limit is 10 and there are 10 active connections, the status should be "repairing".

If this logic is implemented, then testing should be pretty easy as well -- just hold open a number of connections equal to the limit.
___
*[witchcraft/ratelimit/middleware.go, line 50 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbtClg3TK3YoOu6zis:-LcbtClg3TK3YoOu6zit:bhyxjlg) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L50)):*
> ```Go
> func NewInFlightRequestLimitMiddleware(limit int64, matches MatchFunc, healthcheck reporter.HealthComponent) wrouter.RouteHandlerMiddleware {
> 	l := &limiter{
> 		Limit:   limit,
> ```

If provided limit is <= 0, do we care, or should we explicitly set it to 0 (or some other minimum value like "1")?
___
*[witchcraft/ratelimit/middleware.go, line 68 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbsTeD7doLP69n0Rkt:-LcbsTeD7doLP69n0Rku:b-lxvw9s) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L68)):*
> ```Go
> }
> 
> const inFlightThrottledMessage = "Throttling due to too many inflight requests"
> ```

Can we make this "in-flight"?
___
*[witchcraft/ratelimit/middleware.go, line 84 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbrnGY68t_NhQ9O5Al:-LcbrnGY68t_NhQ9O5Am:b5y8v09) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L84)):*
> ```Go
> }
> 
> func (l *limiter) increment(ctx context.Context) bool {
> ```

Can you add a comment (or name the return value) to indicate what the return value means?
___
*[witchcraft/ratelimit/middleware.go, line 86 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbruhQBJHCDXBC34-1:-LcbruhQBJHCDXBC34-2:b-q3muxn) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L86)):*
> ```Go
> func (l *limiter) increment(ctx context.Context) bool {
> 	current := atomic.AddInt64(&l.current, 1)
> 	if current > l.Limit {
> ```

nit: can we invert the conditional to keep the bulk of the logic at a higher level?

```go
if current <= l.Limit {
     return false
}
// other logic
return true
```
___
*[witchcraft/ratelimit/middleware.go, line 102 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-Lcbv6CM04BnekJqhA81:-LcbsK2v3s2Zzi9ZnHDB:btt1am8) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L102)):*
> ```Go
> func (l *limiter) decrement(ctx context.Context) {
> 	current := atomic.AddInt64(&l.current, -1)
> 	if current <= l.Limit {
> ```

nit: since we're not doing anything in either of the "else" cases,  you can combine this check with the rest using an `&&` if you want to do so.


<!-- Sent from Reviewable.io -->

2019-04-16 22:32 UTC, bmoylan reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @bmoylan, @chewr, and @nmiyake)

___
*[integration/ratelimit_test.go, line 118 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbnaBA1ul3bxN20CBW:-LccFSDo4MS4t51dpCh-:b70wwph) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/fc70fb4be24545f0c7bc946a6a04fda2e8af4435/integration/ratelimit_test.go#L118)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

I think this is actually exposing a possible issue with the underlying logic!

As you point out, whenever a request that causes throttling comes in, the function immediately returns an error response and terminates, and sets the service back to "healthy". I think the logic should probably be changed such that the state is only set to healthy when the connection count is 1 less than the limit (rather than the limit itself).

Consider the case where the limit is 10 and we have 10 long-running requests that are effectively hogging all of the connections. In this case, the status would be "healthy", but every subsequent request that comes in will be throttled, set status to "repairing" for a fraction of a second, but then decrement and go back to "healthy" again.

I think the semantic should instead be that the service is "repairing" if it's at capacity (if subsequent matching requests will be throttled) -- so, if the limit is 10 and there are 10 active connections, the status should be "repairing".

If this logic is implemented, then testing should be pretty easy as well -- just hold open a number of connections equal to the limit.
</blockquote></details>

you are right yet again! this makes the behavior more predictable (I think) and also fixes my tests 
___
*[witchcraft/ratelimit/middleware.go, line 68 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbsTeD7doLP69n0Rkt:-LccFedL4LqOFWwyV-c6:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L68)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Can we make this "in-flight"?
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 84 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbrnGY68t_NhQ9O5Al:-LccFg7a53-kT5XQyviG:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L84)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Can you add a comment (or name the return value) to indicate what the return value means?
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 86 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbruhQBJHCDXBC34-1:-LccG2JK0mvgiCpyEY5k:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L86)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

nit: can we invert the conditional to keep the bulk of the logic at a higher level?

```go
if current <= l.Limit {
     return false
}
// other logic
return true
```
</blockquote></details>

Done.
___
*[witchcraft/ratelimit/middleware.go, line 102 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-Lcbv6CM04BnekJqhA81:-LccG1JfCP9PtVxIYpAj:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L102)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

nit: since we're not doing anything in either of the "else" cases,  you can combine this check with the rest using an `&&` if you want to do so.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-16 22:33 UTC, bmoylan reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @chewr and @nmiyake)

___
*[witchcraft/ratelimit/middleware.go, line 50 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbtClg3TK3YoOu6zis:-LccGqX976d6NHVPN8jy:bxec1xm) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L50)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

If provided limit is <= 0, do we care, or should we explicitly set it to 0 (or some other minimum value like "1")?
</blockquote></details>

Good question, right now it would block all requests (which is maybe desirable in some weird scenario) but doesn't feel like there's a lot of safety

On a different note, do you think the limit should be a `refreshable.Int` so it's easily live-reloaded?


<!-- Sent from Reviewable.io -->

2019-04-16 22:40 UTC, nmiyake requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67)* status: all files reviewed, 2 unresolved discussions (waiting on @bmoylan, @chewr, and @nmiyake)

___
*[witchcraft/ratelimit/middleware.go, line 50 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbtClg3TK3YoOu6zis:-LccHrYM6_NgklDHfZYI:bll2ov4) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L50)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Good question, right now it would block all requests (which is maybe desirable in some weird scenario) but doesn't feel like there's a lot of safety

On a different note, do you think the limit should be a `refreshable.Int` so it's easily live-reloaded?
</blockquote></details>

Yeah, I don't think a negative limit makes logical sense, so let's just do a check for that and set to 0 if that's the case. A limit of 0 doesn't make too much sense either, but at least that's logically consistent.

Yes, I think using a refreshable for this value could make sense here.


<!-- Sent from Reviewable.io -->

2019-04-16 22:48 UTC, bmoylan reviewed
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @chewr and @nmiyake)

___
*[witchcraft/ratelimit/middleware.go, line 50 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/67#-LcbtClg3TK3YoOu6zis:-LccKTmI0p8pjqq-Ni1O:b-896fja) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9224e5c34bc993af4f28e5cb2a1c8f9e2e024892/witchcraft/ratelimit/middleware.go#L50)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Yeah, I don't think a negative limit makes logical sense, so let's just do a check for that and set to 0 if that's the case. A limit of 0 doesn't make too much sense either, but at least that's logically consistent.

Yes, I think using a refreshable for this value could make sense here.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2019-04-16 22:54 UTC, nmiyake approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/67)* status: all files reviewed, 1 unresolved discussion (waiting on @chewr and @nmiyake)



<!-- Sent from Reviewable.io -->

2019-04-16 23:40 UTC, bmoylan commented
woo! thanks for the thorough review!

2019-04-16 23:40 UTC, merged