Add `periodic.Option` type for running initial poll before waiting.
palantir/witchcraft-go-server pull request #94
Opened 2019-07-02 21:34 UTC by jamesross3

2019-07-08 18:31 UTC, bmoylan requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/94)* status: all files reviewed, 1 unresolved discussion (waiting on @jamesross3)

___
*[status/health/periodic/source.go, line 116 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/94#-LjHqakMD2YItDM5I64j:-LjHqakMD2YItDM5I64k:bwekkuq) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/8e26d1e4003e4b6e52fd443dbb35bcf677afab04/status/health/periodic/source.go#L116)):*
> ```Go
> 
> func (h *healthCheckSource) runPoll(ctx context.Context) {
> 	if h.initialPoll {
> ```

Let's do this after we create the ticker, so that it does not change the interval between calls (`retryInterval` minus duration of `doPoll`)


<!-- Sent from Reviewable.io -->

2019-07-08 20:52 UTC, bmoylan commented
___
*[status/health/periodic/option.go, line 27 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/94#-LjILzI_1IimZByrKp1k:-LjILzI_1IimZByrKp1l:b-w0lxkg) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/43af893bafece0df5b83c4efbf63331e03da55d4/status/health/periodic/option.go#L27)):*
> ```Go
> }
> 
> func WithInitialPoll() Option {
> ```

can you add godoc explaining what this does?


<!-- Sent from Reviewable.io -->

2019-07-08 22:31 UTC, bmoylan approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/94)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-07-09 00:02 UTC, merged

2019-08-05 21:42 UTC, ashrayjain commented
@bmoylan is there a good reason for this not being the default behaviour?

2019-09-17 13:11 UTC, bmoylan commented
@ashrayjain hm honestly I can't think of a good one off the top of my head. This already runs in a background routine so eagerly running a poll probably doesn't hurt much. 

Note that if we make this the default behavior, it will still have some `REPAIRING` time during the duration of this initial poll.